server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cloud-order?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  application:
    #    user的服务名称
    name: orderservice
    cloud:
      nacos:
        #      nacos服务地址
        server-addr: nacos:8848
        discovery:
          cluster-name: HZ

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10089/eureka


ribbon:
  eager-load:
#    开启饥饿加载
    enabled: true
#     配置饥饿加载的服务名称
    clients:
      -userservice

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则


#远程连接调用
feign:
  httpclient:
    enabled: true
    max-connections: 200 #最大连接数
    max-connections-per-route: 50 #单个路径的最大连接数
