server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cloud-user?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver



#      discovery:
#        cluster-name: HZ
#        namespace: ab8cfec5-fdcd-468d-a896-6c52533b78a7 # dev环境
#        ephemeral: false

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug



#eureka:
#    client:
#      service-url:
#        defaultZone: http://127.0.0.1:10089/eureka

